### ISSUE TITLE
Missing licence 

### ISSUE THREAD

**Issue by mwiley** [watzak/react-native-watermark#3]
You claim all rights reserved to this code, but it's taken from this tutorial, definitely enough to be "substantial portions of the Software".

https://www.raywenderlich.com/30200/avfoundation-tutorial-adding-overlays-and-animations-to-videos

The website claims the code is released under MIT (https://www.raywenderlich.com/faq) so this project should include at least include the license, and to be nice, give credit to the source.

**Comment by mwiley** [comment]
I went ahead and created a pull request. #4

**Comment by watzak** [comment]
@mwiley : Thanx for your help! Actually this repo was meant to be a little playground just for me! Didn't thought that people would checkout this repo as it hasn't had a doku ;)

Appreciate your work ;)

Best Klausi
